# Generated by Django 5.1.5 on 2025-01-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
