# Generated by Django 5.1.5 on 2025-02-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dueTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
